
# name:
#    path: /
#    handler: App\Controller\DefaultController::index

home: 
    path: /
    handler: App\Controller\DefaultController::index

dummy:
    path: /dummy
    handler: App\Controller\DefaultController::dummy

user/:
    add:
      path: /add
      handler: App\Controller\UserController::add

    update:
      path: /update/<int:id>
      handler: App\Controller\UserController::update