<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Exception Error</title>
<style>
body{ color: #777575 !important; margin:0 !important; padding:20px !important; font-family:Arial,Verdana,sans-serif !important;font-weight:normal;  }
h1, h2, h3, h4 {
    margin: 0;
    padding: 0;
    font-weight: normal;
    line-height:48px;
}
</style>
</head>
<body>
<h1>Exception Error</h1>
<section class="head">
	<table>
		<tr><td style="width:15%">Type</td><td><?php echo get_class($e) ?></td></tr>
		<?php if (($message = $e->getMessage())) { ?>
		    <tr><td>Message</td><td><?php echo $message ?></td></tr>
		<?php } ?>
		<?php if (($code = $e->getCode())) { ?>
    		<tr><td>Code</td><td><?php echo $code ?></td></tr>
		<?php } ?>
		<?php if (($file = $e->getFile())) { ?>
		    <tr><td>File</td><td><?php echo $file ?></td></tr>
		<?php } ?>
		<?php if (($line = $e->getLine())) { ?>
		    <tr><td>Line</td><td><?php echo $line ?></td></tr>
		<?php } ?>
	</table>
</section>
<section class="trace">
<?php if (($trace = $e->getTraceAsString())) { ?>
    <h2>Trace</h2>
    <pre><?php echo htmlentities($trace) ?></pre>
<?php } ?>
</section>
</body>
</html>